compose:
  # Compose bootstrap node ip, default is local internal ip
  internal_ip: 172.20.0.25
  # Nginx http server bind port for download files and packages
  nginx_http_port: 8080
  # Registry domain for CRI runtime download images
  imagerepo_domain: kube.registry.local
  registry_https_port: 8081

kubespray:
  # Kubernetes version by default, only support v1.21.5
  kube_version: v1.21.5
  # For deploy HA cluster you must configure a external apiserver access ip
  ##自定义apiserver证书的扩展IP地址和域名，列表
  external_apiserver_access_ip:
  - 127.0.0.1
  # CNI support calico, flannel, canal, cilium
  # Set network plugin to calico with vxlan mode by default
  kube_network_plugin: calico
  ###定义flannle的默认网卡，如果node节点上的默认路由网卡作为flannel的网卡不符合预期，可以手动配置下述网段
  ##flannel_interface_regexp: '172\.20\.1\.*'
  #Container runtime, only support containerd if offline deploy
  container_manager: containerd
  # Now only support host if use containerd as CRI runtime
  etcd_deployment_type: host
  # Settings for etcd event server
  etcd_events_cluster_setup: true
  etcd_events_cluster_enabled: true
  ### 这部分定义数据目录路径，如果不需要定义数据目录的路径，可以直接将这几行注释掉（截止到下个注释），删除data_dir必须同时删除下面的几个配置
  data_dir: /opt
  etcd_data_dir: "{{ data_dir }}/lib/etcd"
  etcd_events_data_dir: "{{ data_dir }}/lib/etcd-events"
  kubelet_data_dir: "{{ data_dir }}/lib/kubelet"
  containerd_storage_dir: "{{ data_dir }}/lib/containerd"
  containerd_state_dir: "{{ data_dir }}/run/containerd"
  pods_log_dir: "{{ data_dir }}/log/pods"
  ###目前暂时不支持containerd的数据目录不加{{data_dir}}
  ### 建议数据盘挂载到/opt下，kubelet和contaienrd都使用同一个分区，不然ephemeral-storage limit功能无法使用
  ###数据目录#####


# Cluster nodes inventory info
inventory:
  all:
    vars:
      ansible_port: 22
      ansible_user: root
      ansible_ssh_pass: Password
      ## ansible_sudo_pass: 123
      # ansible_ssh_private_key_file: /kubespray/config/id_rsa
    hosts:
      node1:
        ### 注意 一定要是系统内的IP地址，不可以写域名和VPCIP、NAT IP等，如果确实有需要配置VPC IP或者NAT IP，就要配置k8s_cluster_used_ip为系统内的IP
        ansible_host: 172.20.0.21
        ## k8s集群的各组件/etcd/网络插件使用的IP地址，默认为ansible_host，如果需要自定义单个节点的IP，就打开取消下面的注释，定义IP地址
        ### 注意 一定要是系统内的IP地址，不可以写域名和VPC IP、NAT IP等
        ## k8s_cluster_used_ip: 192.168.1.1
      node2:
        ### 注意 一定要是IP地址，不可以写域名
        ansible_host: 172.20.0.22
      node3:
        ### 注意 一定要是IP地址，不可以写域名
        ansible_host: 172.20.0.23
      node4:
        ### 注意 一定要是IP地址，不可以写域名
        ansible_host: 172.20.0.24
    children:
      kube_control_plane:
        hosts:
          node1:
          node2:
          node3:
      kube_node:
        hosts:
          node1:
          node2:
          node3:
          node4:
      etcd:
        hosts:
          node1:
          node2:
          node3:
      k8s_cluster:
        children:
          kube_control_plane:
          kube_node:
      gpu:
        hosts: {}
      calico_rr:
        hosts: {}


### default下的参数一般不需要手动配置，脚本会自动配置
### Default parameters ###
## This filed not need config, will auto update,
## if no special requirement, do not modify these parameters.
default:
  # NTP server ip address or domain, default is internal_ip
  ntp_server:
    - internal_ip
  # Registry ip address, default is internal_ip
  registry_ip: internal_ip
  # Offline resource url for download files, default is internal_ip:nginx_http_port
  offline_resources_url: internal_ip:nginx_http_port

  registry_domain: imagerepo_domain:registry_https_port
  # Use nginx and registry provide all offline resources
  offline_resources_enabled: true
  # Image repo in registry
  image_repository: library
  # Kubespray container image for deploy user cluster or scale
  kubespray_image: "kubespray"
  # Auto generate self-signed certificate for registry domain
  generate_domain_crt: true
  # Set false to disable download all container images on all nodes
  download_container: false

  # enable support hubble in cilium
  cilium_enable_hubble: false
  # install hubble-relay, hubble-ui
  cilium_hubble_install: false
  # install hubble-certgen and generate certificates
  cilium_hubble_tls_generate: false
  # Kube Proxy Replacement mode (strict/probe/partial)
  cilium_kube_proxy_replacement: probe

